import './globals.css'
import HeaderApp from "@/components/headerApp"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className='bg-white min-h-dvh'>
        <div>
          <HeaderApp />
          {children}
        </div>
      </body>
    </html>
  )
}
